### ISSUE TITLE
ArrayIndexOutOfBoundsException при подаче на вход меньше 9 слов

### ISSUE THREAD

**Issue by ABashkirova** [MrDeVelopMe/KotLin#1]
В тестовом задании показан пример, что на вход подается строка разделенная пробелами, но нигде не указано, что слов будет ровно 9. 

Имеем проблему:
Подадим на вход меньше восьми слов "Раз два три"  и получим выход за границы массива:
```
раз
два
три
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at MainKt.main(Main.kt:3)

```
Подадим больше, и получим не тот результат, отсортируется только первые девять слов:
```
java -jar Main.jar раз два три четыре пять шесть семь восемь девять десять
раз
два
три
четыре
пять
шесть
семь
восемь
девять
```

**Comment by AndreiSerov** [comment]
It means "Buddy, u shouldn't iterate through fixed range - u should make loop that goes through array elements one by one"

**Comment by MrDeVelopMe** [comment]
Исправил. 2 строчку поменял на for(n in 0..args.size-1)
